<a href="https://colab.research.google.com/github/gtobin28/Linear_Algebra_Coding_Projects/blob/master/Copy_of_Math_242_solve_systems_using_computation_and_rref.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load the preliminary code

In [ ]:
import numpy as np
from numpy import c_

ll = "loaded"

In [ ]:
lll = " correctly!"

def rref(matrix):
    A = np.array(matrix, dtype=np.float64)

    i = 0 # row
    j = 0 # column
    while True:
        # find next nonzero column
        while all(A.T[j] == 0.0):
            j += 1
            # if reached the end, break
            if j == len(A[0]) - 1 : break
        # if a_ij == 0 find first row i_>=i with a 
        # nonzero entry in column j and swap rows i and i_
        if A[i][j] == 0:
            i_ = i
            while A[i_][j] == 0:
                i_ += 1
                # if reached the end, break
                if i_ == len(A) - 1 : break
            A[[i, i_]] = A[[i_, i]]
        # divide ith row a_ij to make it a_ij == 1
        A[i] = A[i] / A[i][j]
        # eliminate all other entries in the jth column by subtracting
        # multiples of of the ith row from the others
        for i_ in range(len(A)):
            if i_ != i:
                A[i_] = A[i_] - A[i] * A[i_][j] / A[i][j]
        # if reached the end, break
        if (i == len(A) - 1) or (j == len(A[0]) - 1): break
        # otherwise, we continue
        i += 1
        j += 1

    return A

print(">> The page ", ll, lll)

>> The page  loaded  correctly!


# Solving Systems using Computation:  An Overview

Suppose we wanted to solve a system like:

$$
\left\{ \begin{array}{rcr} 5x + 6y + 2z & = & -1\\ 4x + 7y + 19 z & = & 2 \\ 3y + 12z & = & 1 \\ \end{array} \right.
$$

First, we create a matrix $A$ to represent the matrix on matrix on the left.  We'll also create a column matrix, or vector, to represent the numbers on the right hand side.  We'll call that vector $\vec{b}$:

In [ ]:
# create the matrix:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])

# create the vector for the right hand side:
b = np.matrix([[-1], [2], [1]])

To verify that we have entered $A$ correctly, or $\vec{b}$ correctly, simply call 

```
print(A)
```

 or 
 
 

```
print(b)
```

and the system will display that element:



In [ ]:
print(A)

[[ 5  6  2]
 [ 4  7 19]
 [ 0  3 12]]


We want to solve the augmented matrix  $\left( A \, | \, \vec{b} \right)$, so we need to create an augmented matrix.  We use:

```
 np.c_(A, b)
```
to create the augmented matrix by putting the $\vec{b}$ vector on the right of the $A$ matrix.  We'll save this new matrix as $M$:


In [ ]:
M = np.c_[A,b]
print(M)

[[ 5  6  2 -1]
 [ 4  7 19  2]
 [ 0  3 12  1]]


Lastly, we'll use te function 

```
rref(M)
```

to provide the reduced row echelon form of the matrix $M$.  Let's print out the result:


In [ ]:
print(rref(M))

[[ 1.          0.          0.          0.45736434]
 [ 0.          1.          0.         -0.62790698]
 [-0.         -0.          1.          0.24031008]]


# Use Computation to check prior homework

We'll use Google Colab to check our solutions to the six systems below, which we solved previously using row operations:

$$
(a) \hspace{.5cm}
\left\{ \begin{array}{rcr} 2x + 2y & = & 5 \\ x - 4y & = & 0 \\ \end{array} \right.
\hspace{1cm}
(b) \hspace{.5cm}
\left\{ \begin{array}{rcr} -x + y &=& 1 \\ x + y &=& 2 \\ \end{array}
\right.
\hspace{1cm}
(c) \hspace{.5cm}
\left\{ \begin{array}{rcr} x - 3y + z & = 1 \\ x + y + 2z & = & 14 \\ \end{array}
\right.
\hspace{1cm}
(d) \hspace{.5cm}
\left\{ \begin{array}{rcr} -x - y &=& 1 \\ -3x -3 y &=& 2 \\ \end{array}
\right.
$$


$$
(e) \hspace{.5cm}
\left\{ \begin{array}{rcr} 4y + z & = & 20 \\ 2x - 2y + z & = & 0 \\ x + z & = & 5 \\ x + y - z & = & 10 \\ \end{array} \right.
\hspace{1cm}
(f) \hspace{.5cm}
\left\{ \begin{array}{rcr} 2x + z + w & = & 5 \\ y - w & = & -1 \\ 3x - z - w & = & 0 \\ 4x + y + 2z + w & = & 9 \\ \end{array}
\right.
$$




The main steps are to:

1) Create the matrix $A$ and column vector $\vec{b}$ for the system using



```
# create the matrix:
A = np.matrix([[5, 6, 2],
               [4, 7, 19],
               [0, 3, 12]])

# create the vector for the right hand side:
b = np.matrix([[-1], [2], [1]])
```


2) Create the augmented matrix $\left( A \, | \, \vec{b} \right)$ using



```
M = np.c_[A,b]
```

3)  Display the reduced row echelon form of $M$ using



```
print(rref(M))
```

You'll do this for each of the six systems of equations from the homework:


$$
(a) \hspace{.5cm}
\left\{ \begin{array}{rcr} 2x + 2y & = & 5 \\ x - 4y & = & 0 \\ \end{array} \right.
$$

$$
(b) \hspace{.5cm}
\left\{ \begin{array}{rcr} -x + y &=& 1 \\ x + y &=& 2 \\ \end{array}
\right.
$$

$$
(c) \hspace{.5cm}
\left\{ \begin{array}{rcr} x - 3y + z & = 1 \\ x + y + 2z & = & 14 \\ \end{array}
\right.
$$

$$
(d) \hspace{.5cm}
\left\{ \begin{array}{rcr} -x - y &=& 1 \\ -3x -3 y &=& 2 \\ \end{array}
\right.
$$

$$
(e) \hspace{.5cm}
\left\{ \begin{array}{rcr} 4y + z & = & 20 \\ 2x - 2y + z & = & 0 \\ x + z & = & 5 \\ x + y - z & = & 10 \\ \end{array} \right.
$$

$$
(f) \hspace{.5cm}
\left\{ \begin{array}{rcr} 2x + z + w & = & 5 \\ y - w & = & -1 \\ 3x - z - w & = & 0 \\ 4x + y + 2z + w & = & 9 \\ \end{array}
\right.
$$