<a href="https://colab.research.google.com/github/gtobin28/Linear_Algebra_Coding_Projects/blob/master/Finding_Determinants_of_Matricies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Import numpy library

import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [3]:
# create the matrix:
M = np.matrix([[1, -1, 0, 0],
               [1, 0, -1, 0],
               [0, 1, -1, 0],
               [0, 0, -1, 1]])

In [4]:
# Find determinant of a matrix M
np.linalg.det(M)

0.0

Homework Problem 2

In [6]:
A = np.matrix([[3, 2, 3],
               [-6, 1, -10],
               [-8, -9, -9]])

B = np.matrix([[1, -2, 1],
               [5, 5, 4],
               [4, 0, 0]])

C = np.matrix([[1, 0, 0],
               [0, 2, 0],
               [-3, -2, 1]])

In [15]:
print(A*B)
print()
print(B*A)

[[ 25   4  11]
 [-41  17  -2]
 [-89 -29 -44]]

[[  7  -9  14]
 [-47 -21 -71]
 [ 12   8  12]]


In [16]:
print(np.linalg.det(A*B), np.linalg.det(B*A))

3067.9999999999973 3067.9999999999973


In [17]:
print(A*C)
print()
print(C*A)

[[ -6  -2   3]
 [ 24  22 -10]
 [ 19   0  -9]]

[[  3   2   3]
 [-12   2 -20]
 [ -5 -17   2]]


In [18]:
print(np.linalg.det(A*C), np.linalg.det(C*A))

-118.00000000000004 -118.00000000000004


In [19]:
print(B*C)
print()
print(C*B)

[[-2 -6  1]
 [-7  2  4]
 [ 4  0  0]]

[[  1  -2   1]
 [ 10  10   8]
 [ -9  -4 -11]]


In [20]:
print(np.linalg.det(B*C), np.linalg.det(C*B))

-103.99999999999999 -104.00000000000007


In [21]:
np.linalg.det(A)

-58.999999999999964