<a href="https://colab.research.google.com/github/gtobin28/Linear_Algebra_Coding_Projects/blob/master/Gram_Schmidt_Process_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# Import numpy library

import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [9]:
# examples of matrix and vector definition

# create the matrix:
Matrix = np.matrix([[1, -1, 0, 0],
               [1, 0, -1, 0],
               [0, 1, -1, 0],
               [0, 0, -1, 1],
               [-1, 0, 0, 1]])


# create the vector for the right hand side:
points = np.matrix([[1], [14], [38], [11], [20]])

In [15]:
# How to do a dot product
np.dot([1,2],[3,4])

11

In [14]:
# How to find magnitude in np
np.sqrt(np.dot([1,2],[1,2]))

2.23606797749979

In [18]:
# Define the original vectors

r1 = [2,4,0,0]
r2 = [1,2,3,6]
r3 = [2,-1,2,-1]
r4 = [1,2,3,4]

# Look at vector r1
r1

[2, 4, 0, 0]

In [22]:
# Find the first nice basis vector u1:

# 1: Pick a new vector
r1

# 2: Subtract the projection of r1 onto the nice basis u1, u2, u3...
#  save this as a temp vector n1
n1 = r1
n1

# 3: Find magnitude of n1
magn1 = np.sqrt(np.dot(n1,n1))

# 4: Create nice basis vector u1
u1 = n1/magn1
u1

array([0.4472136 , 0.89442719, 0.        , 0.        ])

In [23]:
# check u1 has a magnitude 1:
np.dot(u1,u1)

0.9999999999999999

In [40]:
# Find the second nice basis vector u2:

# 1: Pick a new vector
r2

# 2: Subtract the projection of r2 onto the nice basis u1, u2, u3...
#  save this as a temp vector n2
n2 = r2 - np.dot(r2,u1) * u1
n2

# 3: Find magnitude of n2
magn2 = np.sqrt(np.dot(n2,n2))
magn2

# 4: Create nice basis vector u2
u2 = n2/magn2
u2

array([0.        , 0.        , 0.4472136 , 0.89442719])

In [30]:
# check u2 magnitude 1:
np.dot(u2,u2)

0.9999999999999999

In [29]:
# check that u1 and u2 are orthogonal:
np.dot(u1,u2)

0.0

In [34]:
# Find the third nice basis vector u3:

# 1: Pick a new vector
r3

# 2: Subtract the projection of r3 onto the nice basis u1, u2, u3...
#  save this as a temp vector n3
n3 = r3 - np.dot(r3,u1) * u1 - np.dot(r3,u2) * u2
n3

# 3: Find magnitude of n3
magn3 = np.sqrt(np.dot(n3,n3))
magn3

# 4: Create nice basis vector u3
u3 = n3/magn3
u3

array([ 0.63245553, -0.31622777,  0.63245553, -0.31622777])

In [35]:
# check u3 magnitude 1:
np.dot(u3,u3)

1.0

In [39]:
# check that u3 is orthogonal to u1 and u2:
print(np.dot(u1,u3))
print(np.dot(u2,u3))

0.0
0.0


In [41]:
# Find the fourth nice basis vector u4:

# 1: Pick a new vector
r4

# 2: Subtract the projection of r4 onto the nice basis u1, u2, u3...
#  save this as a temp vector n4
n4 = r4 - np.dot(r4,u1) * u1 - np.dot(r4,u2) * u2 - np.dot(r4,u3) * u3
n4

# 3: Find magnitude of n4
magn4 = np.sqrt(np.dot(n4,n4))
magn4

# 4: Create nice basis vector u4
u4 = n4/magn4
u4

array([-0.63245553,  0.31622777,  0.63245553, -0.31622777])

In [42]:
# check u3 magnitude 1:
np.dot(u4,u4)

0.9999999999999998

In [44]:
# check that u3 is orthogonal to u1, u2, and u3:
print(np.dot(u1,u4))
print(np.dot(u2,u4))
print(np.dot(u3,u4))

0.0
9.43689570931383e-16
9.71445146547012e-17
