<a href="https://colab.research.google.com/github/gtobin28/Linear_Algebra_Coding_Projects/blob/master/Math_242_secret_number_Grace_Tobin.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Load the preliminary code

In [3]:
import matplotlib.pyplot as plt
from sympy import Poly
import sympy as sym
import numpy as np
from numpy import c_

# We'll specify that x and t are variables:
x, t = sym.symbols('x, t')

ll = "loaded"

In [4]:
lll = " correctly!"

def rref(matrix):
    A = np.array(matrix, dtype=np.float64)
    
    r = 0 #row
    c = 0 #column

    (maxr, maxc) = A.shape

    prev_row_pivot = -1   # The previous row with a leading term:
    tmp_pivot_row = -1
    this_pivot_row = -1

    for c in range(maxc):  # go through each column
      tmp_pivot_row = -1  # reset the tmp pivot row
      this_pivot_row = -1  # reset this pivot row
      for r in range(maxr):  # Find the leading term in this column below prev_row_pivot
        if ((r > prev_row_pivot) and (A[r][c] != 0.0)):
          tmp_pivot_row = r  # find the new pivot row
      if (tmp_pivot_row > -1):  # we found a candidate for the leading term:
        #swap row this_pivot_row with (prev_row_pivot + 1)
        A[[tmp_pivot_row, prev_row_pivot+1]] = A[[prev_row_pivot + 1, tmp_pivot_row]]
        #set this_pivot_row to prev_row_pivot+1
        this_pivot_row = prev_row_pivot + 1
        #Now, normalize the row based on the pivot value:
        A[ this_pivot_row ] = A[ this_pivot_row ] / A[ this_pivot_row ][c]
        #Then, use this row to force 0's above and below the pivot entry:
        #subtract multiples of of the this_pivot_row row from the others
        for r_ in range(len(A)):
            if r_ != this_pivot_row:
                A[r_] = A[r_] - A[this_pivot_row] * A[r_][c] / A[this_pivot_row][c]
        prev_row_pivot = this_pivot_row
    return A    
    
    

print(">> The page ", ll, lll)

>> The page  loaded  correctly!


# Set up the secret number

You'll encode a secret number $s$ into a 4th or 5th degree polynomial as its vertical intercept.

Once you've chosen $s$, then create a 4th or 5th degree polynomial $f$ such that the vertical intercept is $s$.


In [16]:
# the secret number is s:

s = 3

p = Poly(3+2*x + 3*x**18, x, domain='RR')

p

Poly(3.0*x**18 + 2.0*x + 3.0, x, domain='RR')

In [18]:
#  Evaluate polynomial at 0:
p.eval(x, 0)

# Check that this is your secret number:

3.00000000000000

# Generate your data points

Use this code to generate the data points for your polynomial.  Write teh data on the second page of your handout.  

Writing 

```
p.eval(x, 3)
```

will evaluate $p$ when $x = 3$.  Just change the $3$ to any value to evaluate $p$ at that input.

Remember:  Keep your secret number and polynomial hidden.

In [ ]:
p.eval(x, 3)

1162261487.00000

#  Decode the polynomial from another group

In this section, we set up a linear system to find the polynomial and the secret number which was given to us by another group.

First, set up a linear algebra system to find the polynomial on the handout and then enter the matrix here.  You may have to adjust the size of the matrix below to accommodate your data.

In [9]:
# create the matrix:
A = np.matrix([[1, -3.3, (-3.3)**2, (-3.3)**3, (-3.3)**4],
               [1, -2.5, (-2.5)**2, (-2.5)**3, (-2.5)**4],
               [1, -1.5, (-1.5)**2, (-1.5)**3, (-1.5)**4],
               [1, -0.417, (-0.417)**2, (-0.417)**3, (-0.417)**4],
               [1, 1, 1**2, 1**3, 1**4],
               [1, 1.5, 1.5**2, 1.5**3, 1.5**4]])
 
# create the vector for the right hand side:
b = np.matrix([[14.66], [5.055], [-3.67], [0], [6.108], [18.156]])

#Make sure the system looks appropriate:

print(np.c_[A,b])

[[ 1.00000000e+00 -3.30000000e+00  1.08900000e+01 -3.59370000e+01
   1.18592100e+02  1.46600000e+01]
 [ 1.00000000e+00 -2.50000000e+00  6.25000000e+00 -1.56250000e+01
   3.90625000e+01  5.05500000e+00]
 [ 1.00000000e+00 -1.50000000e+00  2.25000000e+00 -3.37500000e+00
   5.06250000e+00 -3.67000000e+00]
 [ 1.00000000e+00 -4.17000000e-01  1.73889000e-01 -7.25117130e-02
   3.02373843e-02  0.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00  1.00000000e+00  1.00000000e+00
   1.00000000e+00  6.10800000e+00]
 [ 1.00000000e+00  1.50000000e+00  2.25000000e+00  3.37500000e+00
   5.06250000e+00  1.81560000e+01]]


##  Solve using Row Operations:

We'll solve the augmented matrix  $\left( A \, | \, \vec{b} \right)$ using the function

```
rref(np.c_[A,b])
```

to provide the reduced row echelon form of the matrix system $\left(A \, | \, \vec{b} \right)$.


In [10]:
print(rref(np.c_[A,b]))

[[ 1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.]
 [-0. -0. -0.  1.  0.  0.]
 [-0. -0. -0. -0.  1.  0.]
 [-0. -0. -0. -0. -0.  1.]]


## Solve the system using numerical methods:

We can also generate a solution using some more advanced numerical linear algebra techniques contained inside Numpy.

To solve it this way, use:



```
np.linalg.solve(A,b)
```



In [11]:
# Solve the system using a numerical linear algebra solution:
np.linalg.solve(A,b)

LinAlgError: ignored